--- #YAML:1.0
name:               Finance-YahooJPN-Sym2Name
version:            0.04
abstract:           to convert a Japanese stock symbol to the name
author:
    - Masanori HATA <http://www.mihr.net/>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
